#-------------------------------------------------------------#
# 			******* Account Management Api Information START *************
#-------------------------------------------------------------#
#ams.account_mgmt_url = http://localhost:8185/AccountManagementAPI

#For Local -  For Simulator - /PushTxn
#ams.account_mgmt_url = http://localhost:8385/AmsAPI

#For Local Server -  For Simulator - /PushTxn
#ams.account_mgmt_url = http://103.11.153.212:8385/AmsAPI

#ams.account_mgmt_url = http://localhost:8385/AmsAPI
ams.account_mgmt_url = http://192.168.19.33:8385/AmsAPI


#For ISO Txn
#ams.server.account_mgmt_url = http://192.168.19.33:8185/AccountManagementAPI
ams.server.account_mgmt_url = http://192.168.19.33:8385/AmsAPI
#ams.server.account_mgmt_url = http://localhost:8185/AmsAPI


#For multicurrency Local -  For Simulator - /doTransaction
#ams.multiCurrencyAPIurl = http://localhost:8285/AccountManagementAPI

#For multicurrency Local Server -  For Simulator -/doTransaction
#ams.multiCurrencyAPIurl = http://103.11.153.212:8285/AccountManagementAPI
ams.multiCurrencyAPIurl = http://192.168.19.33:8285/AccountManagementAPI



#For credit card 
#ams.creditCardurl = http://103.11.153.212:8585/AccountManagementAPI
ams.creditCardurl = http://localhost:8585/AccountManagementAPI



ams.account_type = /accountType

ams.account = /account

ams.instant_account = /instanceAccount

ams.mccwiseinterestmaster = /mccMaster

ams.mcc_wise_interest = /mcc-wise-interest

ams.mcc_code = /mcc_code

ams.participant_wallet = /participant_wallet

ams.blocked_mcc_account_type_wise = /blocked_mcc_account_type_wise

ams.account_type_wallet = /account_type_wallet

ams.card_account_linkage = /card-account-linkage

ams.credit_limit = /credit_limit

ams.charges_master_list = /getChargeMasterList

ams.account_txn_master = /accountTxnMaster

ams.account_statement = /account-statement

ams.account_load = /account-load

ams.gl_account_load = /gl-account-load

ams.gl_account_type = /gl-account-type

ams.tax_type_config = /tax_type_config

ams.account_type_category = /account_type_category

ams.gl_account_create = /gl-account-create

ams.account_credit_card_txn = /account-credit-card-txn

ams.account_wise_credit_interest = /account-wise-credit-interest

ams.pre_account_master = /preAccountMaster

ams.pre_sub_account_master = /preSubAccountMaster

ams.account_type_charges = /accountTypeCharges

ams.account_wise_kyc_details = /account-wise-kyc-details

ams.notify_by = /notify-by

ams.address_proof_document_type = /address_proof_document_type

ams.identity_proof_document_type = /identity_proof_document_type

ams.channels = /channels

ams.account_txn_limit = /account-txn-limit

ams.gl_account_type_creation = /gl-account-type-creation

ams.wallet_account = /wallet_account

ams.customer_id = /customerId

ams.customer_id_table = /customerIdTable

ams.chargeRelated = /chargeRelatedMaster

ams.revolving_credit_card = /revolvingCreditCard


ams.category_type = /category_type


ams.transaction_type_master =/transaction_type_master


ams.qr_code = /qrcode


ams.tran_master = /tranMaster

ams.revolving_credit_card = /revolvingCreditCard

ams.revolving_credit_card_master = /revolvingCreditCardMstr

ams.revolving_card_txn = /revolvingCreditCardTxn

ams.revolving_card_intrst = /revolvingCreditInterestTxn

ams.transaction_hanlder = /transactionHandler

ams.glaccount_statement = /gl-account-statement

ams.accountWiseCharge = /accountWiseCharge

#property added by ankit
ams.journal_transfer = /journalTransfer
#property added by ankit

ams.denomination_master = /denomination_master

ams.transaction_report= /txnReport


ams.application_name = /applicationName

ams.approve_upgrade_tier = /approve_upgrade_tier

ams.third_party_path = /thirdParty

ams.accountclouser = /accountclouser

ams.fee_type_master = /feeTypeMaster

ams.vat_type_master = /vatTypeMaster

ams.txn_req_res_log = /transactionReqResLog

ams.txn_control = /transactionControl

#-------------------------AMS Download url------------------

#For Local + Local Server
ams.file_download_url=http://localhost:1170/FileDownloaderAPI

#For Docker
#ams.file_download_url = http://cmsfd:8092/FileDownloaderServicev1-0-0-1

ams.export_pdf = /export-pdf

ams.export_excel = /export-excel

ams.country_code_api = /country_code_api

#For Local + Local Server
DOWNLOAD_FILE_FOLDER_PATH=D:\\Sequro\\Speta\\downloadFile\\

#For Docker
#DOWNLOAD_FILE_FOLDER_PATH=/usr/local/tomcat/paths/Sequro/Speta/downloadFile/

#----------------------------------------------------------------------------#
# 			******* Account Management Api Information END *************
#----------------------------------------------------------------------------#