#--------------------------------------------------------------------------------------------------------#
#										 Configuration File												 #	
#					            	******* CARD MANAGEMENT ******										 #	
#--------------------------------------------------------------------------------------------------------#


#API URL#

#For Local
#cms.url=http://localhost:8445/CardManagementAPI

#For Local Server
cms.url=http://localhost:8045/CardManagementAPI

#For Montra
#cms.url=http://localhost:8445/CardManagementAPI

#For Docker
#cms.url=http://cmsbackendservice:8080/CardManagementAPIv1-0-0-1
#cms.url=http://103.11.153.138:8444/CardManagementAPI 

cms.uri.customerAddition=/customerAddition
cms.uri.debitCardIssuance=/debitCardIssuance
cms.uri.accountManagement=/accountManagement
cms.uri.embossRequest=/embossRequest
cms.uri.searchClientCard=/searchClientCard
cms.uri.detailedClientCard=/detailedClientCard
cms.uri.addressMaintainance=/addressMaintainance
cms.uri.emailMaintainance=/emailMaintainance
cms.uri.phoneMaintainance=/phoneMaintainance
cms.uri.limitUpdate=/limitUpdate
cms.uri.cardStatus=/cardStatus
cms.uri.searchCardDetails=/searchCardDetails
cms.uri.pinManagement=/pinManagement
cms.uri.NCMCServiceUpdation=/NCMCServiceUpdation
cms.uri.document=/documentMaintainance
cms.uri.refresh.cache=/refreshCache
cms.uri.addCardScheduler=/scheduleCardToken
cms.uri.addMobileScheduler=/scheduleMobileToken
cms.fundomo.addaccount.url=http://202.21.39.68/addAccountHolder
cms.uri.keyAddition = /keyAddition

cms.uri.cardAccountCreation = /generateCustomerCreditCardNAccount

#END API URL#

#For Local
#emboss.file.path=./cms/emboss

#For Docker
#emboss.file.path = /usr/local/tomcat/paths/cms/emboss

#For Server
emboss.file.path=D:/Sequro/winservice/cardManagement/cms/emboss

#Added by ankit for Session Timeout
server.servlet.session.timeout=180s

#----------------- Login Error Message ------------------#

imps.user.login.fail=Invalid username and password!
imps.user.login.success=You've been logged out successfully.
imps.error.username=Please Enter User Name
imps.error.password=Please Enter Password

#---------------- End Login Error Message ----------------#


#----------------- Login Properties Message ------------------#

imps.user.login.salt.password=1@46!%0*3(7^
imps.superadmin.user=superAdmin
imps.superadmin.password=PlDcr4tPSElQ0FjwSEFQJ7G2LAI4r6du0Pkze+fjU0M=

#----------------- Salt Key --IV ------------------#

imps.user.login.saltKey=ef3ddaf43bb16823582c808d2a83c5c9
imps.user.login.salt.iv=b0fd78db1b095b2cb02c249c3ff7ceb8

#----------------- Login Properties Message ------------------#


#-------------------------------------------------------------------------------------------------------------------------#
#									******** Institution Properties Message	********									  #		
#-------------------------------------------------------------------------------------------------------------------------#

#Add Institution
imps.error.instAddForm.instCode=Please Enter Institution Code
imps.error.instAddForm.instDesc=Please Enter Institution Description

imps.Valid.instAddForm.instCode=Please Enter Valid Institution Code
imps.Valid.instAddForm.instDesc=Please Enter Valid Institution Description

imps.instAddForm.sucess=Institution Added Successfully !
imps.instAddForm.error=Institution Already Added. Please Try Another Institution!
imps.instAddForm.exception=Error occurs While Adding Institution !

imps.instAddForm.instCode.min.size=2
imps.instAddForm.instDesc.min.size=5
imps.error.instAddForm.instCode.min.size=Minimum 2 digit
imps.error.instAddForm.instDesc.min.size=Minimum 4 digit
imps.instAddForm.instCode.max.size=10
imps.instAddForm.instDesc.max.size=25
imps.error.instAddForm.instCode.max.size=Minimum 10 digit
imps.error.instAddForm.instDesc.max.size=Minimum 25 digit

#Edit Institution

imps.instEditForm.institutionDesc=Please Enter Institution Description !
imps.instEditForm.outwardDayAmtLimit=Please Enter Daily Amount Limit !
imps.instEditForm.outwardMonthAmtLimit=Please Enter Monthly Amount Limit !
imps.instEditForm.outwardMinAmtTran=Please Enter Minimum Amount Transaction !
imps.instEditForm.outwardMaxAmtTran=Please Enter Maximum Amount Transaction !
imps.instEditForm.outwardDayMaxTranCount=Please Enter Daily Maximum Transaction Count !
imps.instEditForm.outwardMonthMaxTranCount=Please Enter Monthly Maximum Transaction Count !

imps.Valid.instEditForm.institutionDesc=Please Enter Valid Institution Description !
imps.Valid.instEditForm.outwardDayAmtLimit=Please Enter Valid Daily Amount Limit !
imps.Valid.instEditForm.outwardMonthAmtLimit=Please Enter Valid Monthly Amount Limit !
imps.Valid.instEditForm.outwardMinAmtTran=Please Enter Valid Minimum Amount Transaction !
imps.Valid.instEditForm.outwardMaxAmtTran=Please Enter Valid Maximum Amount Transaction !
imps.Valid.instEditForm.outwardDayMaxTranCount=Please Enter Valid Daily Maximum Transaction Count !
imps.Valid.instEditForm.outwardMonthMaxTranCount=Please Enter Valid Monthly Maximum Transaction Count !

imps.instEditForm.sucess=Request Submitted Successfully !
imps.instEditForm.error=Request Already Pending For Approval !
imps.instEditForm.exception=Error occurs While Editing Institution !

#Approve Institution
imps.Valid.instApproveForm.isEmptyList=Please Select At Least One Record !

imps.instApproveForm.pending=Request Already Pending for Approval !
imps.instApproveForm.sucess=Request Processed Successfully !
imps.instApproveForm.error=Request Already Approved !
imps.instApproveForm.exception=Error occurs While Approve Institution !

#-------------------------------------------------------------------------------------------------------------------------#
#										******** End Institution Properties Message	********							  #		
#-------------------------------------------------------------------------------------------------------------------------#

#-------------------------------------------------------------------------------------------------------------------------#
#										******** User Management Message ********										  #		
#-------------------------------------------------------------------------------------------------------------------------#

#Add user
imps.addUserForm.sucess=Request Submitted Successfully !
imps.addUserForm.error=Request Already Pending For Approval !
imps.addUserForm.exception=Error occurs While Adding User !
imps.addUserForm.empty=Required !
imps.addUserForm.valid.alphaNumeric=allow only AlphaNumeric !
imps.addUserForm.valid.numeric=allow only Numeric !
imps.addUserForm.valid.email=Invalid Email ID !
imps.addUserForm.min=Minimum length should be {0}
imps.addUserForm.max=Maximum length should be {0}
imps.addUserForm.userID.min=2
imps.addUserForm.userID.max=10
imps.addUserForm.firstName.min=2
imps.addUserForm.firstName.max=10
imps.addUserForm.lastName.min=2
imps.addUserForm.lastName.max=10
imps.addUserForm.mobileNo.min=10
imps.addUserForm.mobileNo.max=12
imps.addUserForm.emailID.min=5
imps.addUserForm.emailID.max=50
imps.addUserForm.secQueAns.min=2
imps.addUserForm.secQueAns.max=20

#Approval User
imps.getApprovalUserForm.exception=Error occurs While Approval User Form !
imps.approvalUserForm.sucess=Request {0} Successfully !
imps.approvalUserForm.error=Request Already Approved !
imps.approvalUserForm.exception=Error occurs While Approving request !


#Edit User
imps.editUserForm.sucess=Request Submitted Successfully !
imps.editUserForm.error=Request Already Pending For Approval !
imps.editUserForm.exception=Error occurs While Adding User !
#-------------------------------------------------------------------------------------------------------------------------#
#										******** End User Management Message ********									  #		
#-------------------------------------------------------------------------------------------------------------------------#



#-------------------------------------------------------------------------------------------------------------------------#
#										******** Channel Management Message ********									  #		
#-------------------------------------------------------------------------------------------------------------------------#


#----------------- Channel Error Message ------------------#

channel.ChannelName.empty=Please Enter Channel name
channel.ChannelPassword.empty=Please Enter Password
channel.ChannelSMSFlag.empty=Please select Channel SMS Flag
channel.OutwardDayAmtLimit.empty=Please Enter Outward Day Amount Limit
channel.OutwardMonthAmtLimit.empty=Please Enter Outward Month Amount Limit
channel.OutwardMinAmtTran.empty=Please Enter Outward Minimum Amount Tran
channel.OutwardMaxAmtTran.empty=Please Enter Outward Maximum Amount Tran
channel.OutwardDayMaxTranCount.empty=Please Enter Outward Day Maximum Tran Count
channel.OutwardMonthMaxTranCount.empty=Please Enter Outward Month Maximum Tran Count

#-----------------Add Channel Property Message ------------------#

imps.channel.password.secretkey=ab^&h!lK

imps.channelForm.sucess=Channel Added Successfully !
imps.channelForm.error=Channel Already Added. Please Try Another Channel!
imps.channelForm.exception=Error occurs While Adding Channel !

imps.addChannelForm.legth.min.size=5
imps.addChannelForm.legth.max.size=15
imps.Valid.addChannelForm.channelNameLength=Channel Name in between 5 and 15.
imps.Valid.addChannelForm.channelName=Please Enter Valid Channel Name.


imps.Valid.addChannelForm.outwardDayAmtLimit=Daily Amount Limit in between 2 and 8.
imps.Valid.addChannel.outwardDayAmtLimit=Please Enter Valid Daily Amount Limit !


imps.Valid.addChannelForm.outwardMonthAmtLimit=Monthly Amount Limit in between 2 and 8.
imps.Valid.addChannel.outwardMonthAmtLimit=Please Enter Valid Monthly Amount Limit !
 

imps.Valid.addChannelForm.outwardMinAmtTran=Min Amount Transaction in between 2 and 8.
imps.Valid.addChannel.outwardMinAmtTran=Please Enter Valid Min Amount Transaction !    


imps.Valid.addChannelForm.outwardMaxAmtTran=Maximum Amount Transaction in between 2 and 8.
imps.Valid.addChannel.outwardMaxAmtTran=Please Enter Valid Max Amount Transaction !

imps.addChannelForm.outwardDayMaxTranCount.min.size=1
imps.addChannelForm.outwardDayMaxTranCount.max.size=8
imps.Valid.addChannelForm.outwardDayMaxTranCount=Daily Max Transaction Count in between 1 and 8.
imps.Valid.addChannel.outwardDayMaxTranCount=Please Enter Valid Daily Max Transaction Count !

imps.addChannelForm.outwardMonthMaxTranCount.min.size=1
imps.addChannelForm.outwardMonthMaxTranCount.max.size=8
imps.Valid.addChannelForm.outwardMonthMaxTranCount=Monthly Max Transaction Count in between 1 and 8.
imps.Valid.addChannel.outwardMonthMaxTranCount=Please Enter Valid Monthly Max Transaction Count !
#-----------------Edit Channel Property Message ------------------#

imps.EditchannelForm.sucess=Request Processed Successfully !
imps.EditchannelForm.error=Request Already Pending For Approval !
imps.EditchannelForm.exception=Error occurs While Editing Channel !


imps.EditchannelForm.duplcate=Channel is already pending for approval !

imps.editChannelForm.legth.min.size=3
imps.editChannelForm.legth.max.size=15
imps.Valid.editChannelForm.channelNameLength=Channel Name in between 3 and 15.
imps.Valid.editChannelForm.channelName=Please Enter Valid Channel Name.


imps.Valid.editChannelForm.outwardDayAmtLimit=Daily Amount Limit in between 2 and 8.
imps.Valid.editChannel.outwardDayAmtLimit=Please Enter Valid Daily Amount Limit !


imps.Valid.editChannelForm.outwardMonthAmtLimit=Monthly Amount Limit in between 2 and 8.
imps.Valid.editChannel.outwardMonthAmtLimit=Please Enter Valid Monthly Amount Limit !
 

imps.Valid.editChannelForm.outwardMinAmtTran=Min Amount Transaction in between 2 and 8.
imps.Valid.editChannel.outwardMinAmtTran=Please Enter Valid Min Amount Transaction !    


imps.Valid.editChannelForm.outwardMaxAmtTran=Maximum Amount Transaction in between 2 and 8.
imps.Valid.editChannel.outwardMaxAmtTran=Please Enter Valid Max Amount Transaction !

imps.editChannelForm.outwardDayMaxTranCount.min.size=1
imps.editChannelForm.outwardDayMaxTranCount.max.size=8
imps.Valid.editChannelForm.outwardDayMaxTranCount=Daily Max Transaction Count in between 1 and 8.
imps.Valid.editChannel.outwardDayMaxTranCount=Please Enter Valid Daily Max Transaction Count !

imps.editChannelForm.outwardMonthMaxTranCount.min.size=1
imps.editChannelForm.outwardMonthMaxTranCount.max.size=8
imps.Valid.editChannelForm.outwardMonthMaxTranCount=Monthly Max Transaction Count in between 1 and 8.
imps.Valid.editChannel.outwardMonthMaxTranCount=Please Enter Valid Monthly Max Transaction Count !

imps.channelApproveForm.pending=Request Already Pending for Approval !
imps.channelApproveForm.sucess=Request Processed Successfully !
imps.channelApproveForm.error=Request Already Approved !
imps.channelApproveForm.exception=Error occurs While Approve Institution !

#-------------------------------------------------------------------------------------------------------------------------#
#										******** END Channel Management Message ********								  #		
#-------------------------------------------------------------------------------------------------------------------------#


#-------------------------------------------------------------------------------------------------------------------------#
#										******** Role Management Message ********								 		  #		
#-------------------------------------------------------------------------------------------------------------------------#

imps.role.add.success=Role has been added successfully. Please initiate checker for the same.
imps.role.add.failure=Error occurred while adding role.
imps.role.add.duplicate=Duplicate Role is being added. Please enter different role details.
imps.role.sql.exception=An internal error has been occurred.

imps.role.approve.success=Request Processed Successfully !
imps.role.approve.error=Internal error occurred while approving/rejecting role.
imps.role.approve.no.record=No record pending for approval.
imps.role.approve.select.blank=Please select role to approve/reject.
imps.role.approve.remark.blank=Please Enter Remarks.

imps.role.edit.success=Role has been edited successfully. Please initiate checker for the same.
imps.role.edit.failure=Error occurred while editing role.
imps.role.edit.no.data=No role found to edit.
imps.role.edit.search.failure=Error occurred while searching role for entered criteria.
imps.role.edit.fetch.privileges=Error occurred while fetching role privileges.
imps.role.roleName.no.select=Please select role to edit.
imps.role.approval.pending=Request already pending for approval.

imps.role.roleId.blank=Please Select Role.
imps.role.roleName.blank=Please Enter Role Name.
imps.role.description.blank=Please Enter Role Description.
imps.role.menuids.blank=Please Select Privileges.

imps.role.invalid.roleId=Please Select Role.
imps.role.invalid.roleName=Please Enter Valid Role Name.
imps.role.invalid.description=Please Enter Valid Role Description.
imps.role.invalid.remark=Please Enter Valid Remarks.

imps.role.view.no.record=No record found to view.

imps.role.name.min.length=5
imps.role.name.max.length=20
imps.role.name.min.length.invalid=Minimum length should be 5
imps.role.name.max.length.invalid=Maximum length should be 20

imps.role.desc.min.length=5
imps.role.desc.max.length=20
imps.role.desc.min.length.invalid=Minimum length should be 5
imps.role.desc.max.length.invalid=Maximum length should be 20

imps.role.remark.min.length=5
imps.role.remark.max.length=50
imps.role.remark.min.length.invalid=Minimum length should be 5
imps.role.remark.max.length.invalid=Maximum length should be 50

#-------------------------------------------------------------------------------------------------------------------------#
#										******** END Role Management Message ********								 	  #		
#-------------------------------------------------------------------------------------------------------------------------#


#-------------------------------------------------------------------------------------------------------------------------#
#										******** Report Management Message ********		   							 	  #		
#-------------------------------------------------------------------------------------------------------------------------#

imps.report.fromDate=Required
imps.report.toDate=Required
imps.report.userName=Required
imps.report.status=Required
imps.report.formDate.invalid=Invalid Date Format
imps.report.toDate.invalid=Invalid Date Format

#-------------------------------------------------------------------------------------------------------------------------#
#										******** END Report Management Message ********								 	  #		
#-------------------------------------------------------------------------------------------------------------------------#


#---------------------------------------------------------------------------------------------------------------#
#									*********** File Upload *************										#
#---------------------------------------------------------------------------------------------------------------#

temp_file_path=./cms/upload/

#temp_file_path=D:/cms/upload/

#-------------------------------------------------------------#
# 			******* Account Management Api Information START *************
#-------------------------------------------------------------#
#ams.account_mgmt_url = http://localhost:8485/AccountManagementAPI
ams.account_mgmt_url = http://103.11.153.212:8485/AccountManagementAPI

ams.account_type = /accountType

ams.account = /account

ams.instant_account = /instanceAccount

ams.mccwiseinterestmaster = /mccMaster

ams.mcc_code = /mcc_code

ams.participant_wallet = /participant_wallet

ams.blocked_mcc_account_type_wise = /blocked_mcc_account_type_wise

ams.account_type_wallet = /account_type_wallet

ams.credit_limit = /credit_limit

ams.charges_master_list = /getChargeMasterList

ams.account_txn_master = /accountTxnMaster

ams.bulk_transfer = /bulkTransfer

ams.file_download_url=http://localhost:1170/FileDownloaderAPI

ams.export_pdf = /export-pdf

ams.export_excel = /export-excel

DOWNLOAD_FILE_FOLDER_PATH=E:\\Sequro\\Speta\\downloadFile\\
#----------------------------------------------------------------------------#
# 			******* Account Management Api Information END *************
#----------------------------------------------------------------------------#

#-------------------SSL Configuration---------------------#


#For Docker-SSL
#keystoreFile=/usr/local/tomcat/paths/cms_montra_org.pfx
#keystoreFile=cms_montra_org.pfx

#For Docker
#EncDeckeystoreFile=/usr/local/tomcat/paths/key.txt

#For Local
EncDeckeystoreFile=E:\\PrashantT\\SEQURO\\Card_Management\\Card_Management\\src\\key.txt

#For montra
#EncDeckeystoreFile = D:\\Sequro\\winservice\\cardManagement\\cms\\key.txt

server.ssl.key-store=classpath:cms_montra_org.pfx
server.ssl.key-store-password=Cmsuser@123
server.ssl.keyStoreType=PKCS12
server.servlet.force-ssl=true
server.ssl.enabled=true
