spring.main.allow-bean-definition-overriding=true
hsmip=10.239.29.6
hsmport=9001

#For Local
#server.port=8445

#For Docker
#server.port=8080

#For Local Server
server.port=8045

hsm.cvk=UF825D28BE1D9748222F5FB89EC17906B
hsm.cvv2=000
hsm.icvv=999

#For Local
#emboss.file.path=./cms/emboss

#For Docker
#emboss.file.path = /usr/local/tomcat/paths/cms/emboss

#For Local Server
emboss.file.path = D:/Sequro/winservice/cardManagement/cms/emboss


log.logger.org.springframework.aop.framework.Cglib2AopProxy = ERROR

#For Docker
#server.servlet.context-path=/CardManagementAPIv1-0-0-1

#For Local 
server.servlet.context-path=/CardManagementAPI

txnip=127.0.0.1
#databaseUsername=${DB_USER}
#databasePassword=${DB_PASS}
#txnport=2230
txnport=3306
#hsmip=192.168.19.4


#ipport=${IP_PORT}
#ip=${IP}
#port=${PORT}

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

#key = h?4W~qQ%


keystoreFile = key.txt
#keystoreFile = /usr/local/tomcat/paths/key.txt