
#--------------------------------------------------------------------------------------------------------#
#									DataBase Configuration File											 #	
#					            	******* CMS SEQURO ******											 #	
#--------------------------------------------------------------------------------------------------------#

cms.db.DriverClassName=com.mysql.jdbc.Driver

cms.db.URL=jdbc:mysql://localhost:3306/traneco_cmsdb
#cms.db.URL=jdbc:mysql://${IP_PORT}/traneco_cmsdb
#imps.db.URL=jdbc:mysql://103.11.153.138:3306/traneco_cmsdb


#cms.db.UserName=${DB_USER}
cms.db.UserName=root
#cms.db.Password=${DB_PASS}
cms.db.Password = SEP@ssw0rd123
cms.db.SetMaxActive=5

#For Sequro
#cardmgt.db.URL=jdbc:mysql://localhost:3306/cardmanagement
#cardmgt.db.URL=jdbc:mysql://${IP_PORT}/cardmanagement
#cardmgt.db.URL=jdbc:mysql://103.11.153.138:3306/cardmanagement

#For Montra
cardmgt.db.URL=jdbc:mysql://localhost:3306/cardmanagement_montra



accountmgt.db.URL=jdbc:mysql://localhost:3306/account_management_sequro
#accountmgt.db.URL=jdbc:mysql://${IP_PORT}/account_management 

