
log4j.rootLogger=DEBUG,ERROR, stdout, file, R
#log4j.rootLogger=INFO, Appender1, Appender2

# Redirect log messages to console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n


# FIRST_APPENDER - used to log messages in the admin-logs.log file.
log4j.logger.FIRST_APPENDER=DEBUG,ERROR, FIRST_APPENDER
log4j.appender.FIRST_APPENDER=org.apache.log4j.RollingFileAppender
log4j.appender.FIRST_APPENDER.maxFileSize=10MB
log4j.appender.FIRST_APPENDER.MaxBackupIndex=10
log4j.appender.FIRST_APPENDER.layout=org.apache.log4j.PatternLayout
log4j.appender.FIRST_APPENDER.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
#log4j.appender.FIRST_APPENDER.File=E:/cms/log/Spring.log
#log4j.appender.FIRST_APPENDER.File=D:/Sequro/winservice/cms/log/Spring.log

#log4j.appender.FIRST_APPENDER.File=D:/Sequro/winservice/cardManagement/log/Spring.log
log4j.appender.FIRST_APPENDER.File=D:/Sequro/winservice/cardManagement-Montra/log/Spring.log
#log4j.appender.FIRST_APPENDER.File=/usr/local/tomcat/paths/Sequro/winservice/cms/log/Spring.log


# SECOND_APPENDER - used to log messages in the report-logs.log file.
log4j.logger.SECOND_APPENDER=DEBUG,ERROR, SECOND_APPENDER
log4j.appender.SECOND_APPENDER=org.apache.log4j.RollingFileAppender
log4j.appender.SECOND_APPENDER.maxFileSize=10MB
log4j.appender.SECOND_APPENDER.layout=org.apache.log4j.PatternLayout
log4j.appender.SECOND_APPENDER.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
#log4j.appender.SECOND_APPENDER.File=E:/cms/log/imps.log

#log4j.appender.SECOND_APPENDER.File=D:/Sequro/winservice/cms/log/imps.log

#log4j.appender.SECOND_APPENDER.File=D:/Sequro/winservice/cardManagement/log/imps.log
log4j.appender.SECOND_APPENDER.File=D:/Sequro/winservice/cardManagement-Montra/log/imps.log
#log4j.appender.SECOND_APPENDER.File=/usr/local/tomcat/paths/Sequro/winservice/cms/log/cms.log

# Mentions the package path to write logs separately



#log4j.logger.org=DEBUG,FIRST_APPENDER 
log4j.logger.com.traneco=DEBUG,SECOND_APPENDER


#log4j.appender.R=org.apache.log4j.RollingFileAppender
#log4j.appender.R.File=D:/Sequro/winservice/cardManagement/log/example.log
